# Generated by Django 5.1.2 on 2025-01-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_resume_uploaded_at_resume_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='job_role',
            field=models.CharField(max_length=255),
        ),
    ]
