# Generated by Django 5.1.5 on 2025-01-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_userskills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSkills',
        ),
    ]
