# Generated by Django 5.1.5 on 2025-02-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
