# Generated by Django 5.1.5 on 2025-02-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
