# Generated by Django 5.1.5 on 2025-02-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_resume_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
    ]
