# Generated by Django 5.1.5 on 2025-02-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_resume_extracted_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='extracted_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
