# Generated by Django 5.1.5 on 2025-04-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_resume_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
