# Generated by Django 5.1.5 on 2025-04-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_interviewresponse_evaluated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='evaluated_at',
        ),
    ]
