# Generated by Django 5.1.5 on 2025-04-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_interviewresponse_evaluated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
